feat: Records the start and end times of a track.
jitsi/rtcstats-server pull request #87
Opened 2022-08-04 07:31 UTC by gpolitis

2022-08-04 22:35 UTC, nils-ohlmeier requested changes
I think this PR is missing at least the changes needed in the Firehose SQL schema.

But based on my comments below I think it also missing change to the Firehose connector itself.

2022-08-04 22:35 UTC, nils-ohlmeier commented on src/features/quality-stats/QualityStatsCollector.js
> +            pcData[ssrc].endTime = timestamp;
I would protect this with a check if `timestamp` is not undefined. That should prevent setting `endTime` accidentally. And as a plus allows to call `_getTrackData()` without a timestamp if needed.

I would compare the start and end time and rather set them to the same values, rather then creating negative track durations by allowing `endTime < startTime`.

2022-08-04 22:35 UTC, nils-ohlmeier commented on src/features/quality-stats/StatsAggregator.js
> +        stats.endTime = getSQLTimestamp(endTime);
I think this conversion is a level too high for my taste. I would prefer if this conversion happens in the Firehose connector. That would leave the option to write data into a non-SQL DB if needed.

2022-08-09 09:57 UTC, andrei-gavrilescu commented
LGTM!

2022-08-10 15:18 UTC, merged